// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqIvlUjq1cKqzAXJ719WzA5ZDF0CHsjL4',
    appId: '1:783155194401:web:02e6a164040a1bc5489160',
    messagingSenderId: '783155194401',
    projectId: 'defi-app-9420e',
    authDomain: 'defi-app-9420e.firebaseapp.com',
    storageBucket: 'defi-app-9420e.appspot.com',
    measurementId: 'G-Q6PS5X73Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMueEh92gPylr3sdxuTksO3QwyiymfWes',
    appId: '1:783155194401:android:f8a6571e9c3698e3489160',
    messagingSenderId: '783155194401',
    projectId: 'defi-app-9420e',
    storageBucket: 'defi-app-9420e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJzok27lMkpKTarM2iIsuLinHVvd0gkzE',
    appId: '1:783155194401:ios:eedaa80903bd2ca5489160',
    messagingSenderId: '783155194401',
    projectId: 'defi-app-9420e',
    storageBucket: 'defi-app-9420e.appspot.com',
    iosClientId: '783155194401-idtu7i3m0l7o0v21g18rrhsuq7scp6u1.apps.googleusercontent.com',
    iosBundleId: 'com.example.defiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJzok27lMkpKTarM2iIsuLinHVvd0gkzE',
    appId: '1:783155194401:ios:eedaa80903bd2ca5489160',
    messagingSenderId: '783155194401',
    projectId: 'defi-app-9420e',
    storageBucket: 'defi-app-9420e.appspot.com',
    iosClientId: '783155194401-idtu7i3m0l7o0v21g18rrhsuq7scp6u1.apps.googleusercontent.com',
    iosBundleId: 'com.example.defiApp',
  );
}
